

CREATE TABLE CivilServices_CSID_HID_S (
    CSID INTEGER NOT NULL,
    HID INTEGER NOT NULL, 
    S INTEGER NOT NULL,
    PRIMARY KEY (CSID, HID)
    FOREIGN KEY (CSID) REFERENCES CivilServices_CSID_PN (CSID),
    FOREIGN KEY (HID) REFERENCES CivilServices_HID_HS_HZ (HID),
);

CREATE TABLE CivilServices_CSID_PN (
    CSID INTEGER NOT NULL,
    PN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (CSID)
);

CREATE TABLE CivilServices_HID_HS_HZ (
    HID INTEGER NOT NULL, 
    HS CHARACTER VARYING NOT NULL,
    HZ INTEGER NOT NULL, 
    PRIMARY KEY (HID)
    FOREIGN KEY (HZ) REFERENCES CivilServices_HZ_HC (HZ),
);

CREATE TABLE CivilServices_HZ_HC (
    HZ INTEGER NOT NULL, 
    HC CHARACTER VARYING NOT NULL,
    PRIMARY KEY (HZ)
);
